import pandas as pd
import torch
from _typeshed import Incomplete
from dataclasses import dataclass, field
from typing import Any, Literal, Protocol

__all__ = ['MetricsEngine', 'DriftMetrics', 'ConfidenceMetrics', 'AlertConfig', 'AlertCallback']

@dataclass
class DriftMetrics:
    js_divergence: float
    status: Literal['healthy', 'warning', 'critical']
    affected_features: list[str]
    timestamp: str
    details: dict[str, float] = field(default_factory=dict)
    def to_dict(self) -> dict[str, Any]: ...

@dataclass
class ConfidenceMetrics:
    top1_confidence: float
    top5_confidence: float
    entropy: float
    num_samples: int
    calibration_error: float | None = ...
    def to_dict(self) -> dict[str, Any]: ...

@dataclass
class AlertConfig:
    val_loss_spike_threshold: float = ...
    accuracy_drop_threshold: float = ...
    gradient_explosion_threshold: float = ...
    enable_email_alerts: bool = ...
    enable_slack_alerts: bool = ...

class AlertCallback(Protocol):
    def __call__(self, alert_type: str, message: str, metrics: dict[str, Any]) -> None: ...

class MetricsEngine:
    use_wandb: Incomplete
    gradient_accumulation_steps: Incomplete
    drift_threshold_warning: Incomplete
    drift_threshold_critical: Incomplete
    alert_config: Incomplete
    alert_callbacks: Incomplete
    experiment_db: Incomplete
    run_id: Incomplete
    metrics_history: list[dict[str, Any]]
    drift_history: list[DriftMetrics]
    reference_profile: dict[str, Any] | None
    def __init__(self, use_wandb: bool = True, gradient_accumulation_steps: int = 1, drift_threshold_warning: float = 0.1, drift_threshold_critical: float = 0.2, alert_config: AlertConfig | None = None, alert_callbacks: list[AlertCallback] | None = None, experiment_db: Any | None = None, run_id: int | None = None) -> None: ...
    def log_epoch(self, epoch: int, train_metrics: dict[str, float], val_metrics: dict[str, float], learning_rate: float, gradient_norm: float, epoch_duration: float, reference_profile: dict[str, Any] | None = None, current_profile: dict[str, Any] | None = None) -> DriftMetrics | None: ...
    def log_scalar(self, metric_name: str, value: float, step: int | None = None, commit: bool = True) -> None: ...
    def log_confidence(self, logits: torch.Tensor, labels: torch.Tensor, step: int, ignore_index: int = -100) -> ConfidenceMetrics: ...
    def check_drift(self, reference_profile: dict[str, Any], current_profile: dict[str, Any]) -> DriftMetrics: ...
    def trigger_alert(self, alert_type: str, message: str, metrics: dict[str, Any]) -> None: ...
    def has_alerts(self) -> bool: ...
    def get_alerts(self, clear: bool = True) -> list[dict[str, Any]]: ...
    def get_summary(self) -> pd.DataFrame: ...
    def get_step_metrics(self) -> pd.DataFrame: ...
    def get_best_epoch(self, metric: str = 'val/loss', mode: Literal['min', 'max'] = 'min') -> int: ...
