import torch.nn as nn
from _typeshed import Incomplete
from datasets import Dataset as HFDataset
from torch.utils.data import DataLoader, Dataset
from types import SimpleNamespace
from typing import Any, Protocol
from utils.training.engine.data import UniversalDataModule
from utils.training.task_spec import TaskSpec
from utils.training.training_config import TrainingConfig

__all__ = ['Trainer', 'TrainingHooks', 'DefaultHooks']

class TrainingHooks(Protocol):
    def on_training_start(self) -> None: ...
    def on_epoch_start(self, epoch: int) -> None: ...
    def on_batch_end(self, batch_idx: int, loss: float) -> None: ...
    def on_validation_end(self, metrics: dict[str, float]) -> None: ...
    def on_epoch_end(self, epoch: int, metrics: dict[str, float]) -> None: ...
    def on_training_end(self) -> None: ...

class DefaultHooks:
    def on_training_start(self) -> None: ...
    def on_epoch_start(self, epoch: int) -> None: ...
    def on_batch_end(self, batch_idx: int, loss: float) -> None: ...
    def on_validation_end(self, metrics: dict[str, float]) -> None: ...
    def on_epoch_end(self, epoch: int, metrics: dict[str, float]) -> None: ...
    def on_training_end(self) -> None: ...

class Trainer:
    model: Incomplete
    config: Incomplete
    training_config: Incomplete
    task_spec: Incomplete
    hooks: Incomplete
    device: Incomplete
    checkpoint_manager: Incomplete
    metrics_tracker: Incomplete
    loss_strategy: Incomplete
    gradient_monitor: Incomplete
    optimizer: Incomplete
    gradient_accumulator: Incomplete
    scheduler: Incomplete
    data_module: UniversalDataModule | None
    def __init__(self, model: nn.Module, config: SimpleNamespace | Any, training_config: TrainingConfig, task_spec: TaskSpec | None = None, tokenizer: Any | None = None, data_collator: Incomplete | None = None, hooks: TrainingHooks | None = None) -> None: ...
    def train(self, train_data: Dataset | HFDataset | DataLoader, val_data: Dataset | HFDataset | DataLoader | None = None, resume_from: str | None = None) -> dict[str, Any]: ...
