"""
Transformer Builder Colab Utilities

Production-ready utilities for training, validating, and exporting
transformer models generated by the Transformer Builder platform.

Version: 2.0.0
License: MIT
"""

__version__ = "2.0.0"

# Core adapters (Tasks 1.3, 1.4, 2.1 complete)
from .adapters.model_adapter import (
    ModelSignatureInspector,
    ComputationalGraphExecutor,
    UniversalModelAdapter
)

# Tokenization (Tasks 2.2-2.7 complete)
from .tokenization.adaptive_tokenizer import AdaptiveTokenizer
from .tokenization.bpe_trainer import FastBPETrainer, BPETrainerConfig
from .tokenization.character_tokenizer import CharacterLevelTokenizer
from .tokenization.validator import TokenizerValidator
from .tokenization.data_module import AdaptiveTokenizerDataModule, SimpleDataModule

# Training (will be available after implementation)
# from .training.dataset_utilities import DatasetLoader, DatasetUploader
# from .training.checkpoint_manager import CheckpointManager
# from .training.training_core import TrainingCoordinator
# from .training.export_utilities import (
#     ONNXExporter,
#     TorchScriptExporter,
#     ModelCardGenerator
# )

# UI (will be available after implementation)
# from .ui.setup_wizard import SetupWizard

# Test functions (backward compatibility - already available)
from .test_functions import *

__all__ = [
    # Version
    '__version__',

    # Adapters
    'ModelSignatureInspector',
    'ComputationalGraphExecutor',
    'UniversalModelAdapter',

    # Tokenization
    'AdaptiveTokenizer',
    'FastBPETrainer',
    'BPETrainerConfig',
    'CharacterLevelTokenizer',
    'TokenizerValidator',
    'AdaptiveTokenizerDataModule',
    'SimpleDataModule',

    # Training (coming soon)
    # 'DatasetLoader',
    # 'DatasetUploader',
    # 'CheckpointManager',
    # 'TrainingCoordinator',
    # 'ONNXExporter',
    # 'TorchScriptExporter',
    # 'ModelCardGenerator',

    # UI (coming soon)
    # 'SetupWizard',

    # Test functions (available now - re-exported from test_functions.py)
    'test_shape_robustness',
    'test_gradient_flow',
    'test_output_stability',
    'test_parameter_initialization',
    'test_memory_footprint',
    'test_inference_speed',
    'test_attention_patterns',
    'test_attribution_analysis',
    'test_robustness',
    'test_fine_tuning',
    'test_hyperparameter_search',
    'test_benchmark_comparison',
    'run_all_tier1_tests',
    'run_all_tier2_tests',
    'run_all_tests',
]
